[build]
  functions = "netlify-functions"
  publish = "dist"

[dev]
  functions = "netlify-functions"
  port = 8888
  publish = "dist"

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
