plugins = []
functionsDirectory = "C:\\Users\\user\\Desktop\\React Series\\my-first-project\\netlify-functions"
functionsDirectoryOrigin = "config-v1"
headers = []

[dev]
functions = "netlify-functions"
port = 8888.0
publish = "dist"

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\user\\Desktop\\React Series\\my-first-project\\dist"
publishOrigin = "config"
commandOrigin = "ui"
command = "npm run build"
functions = "C:\\Users\\user\\Desktop\\React Series\\my-first-project\\netlify-functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]